const { chromium } = require("playwright");
const fs = require("node:fs/promises");
const path = require("node:path");
const http = require("node:http");
const assert = require("node:assert/strict");

const root = path.resolve(__dirname, "..");
const output = path.join(root, "outputs", "app-review-20260907");
const types = { ".html": "text/html", ".js": "text/javascript", ".css": "text/css", ".json": "application/json", ".png": "image/png", ".jpg": "image/jpeg" };
const server = http.createServer(async (req, res) => {
  try {
    const pathname = decodeURIComponent(new URL(req.url, "http://localhost").pathname);
    const file = path.resolve(root, `.${pathname === "/" ? "/index.html" : pathname}`);
    if (!file.startsWith(root + path.sep)) throw new Error("Invalid path");
    const data = await fs.readFile(file);
    res.writeHead(200, { "Content-Type": types[path.extname(file)] || "application/octet-stream" });
    res.end(data);
  } catch { res.writeHead(404); res.end(); }
});

(async () => {
  await fs.mkdir(output, { recursive: true });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  let browser;
  try {
    browser = await chromium.launch({ headless: true, channel: "chrome" });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
    const page = await context.newPage();
    page.setDefaultTimeout(15000);
    const errors = [];
    const requests = [];
    page.on("pageerror", (error) => errors.push(error.message));
    page.on("request", (request) => requests.push(request.url()));
    page.on("dialog", (dialog) => dialog.accept());
    await context.route("**/*", (route) => route.request().url().startsWith("http://127.0.0.1:") ? route.continue() : route.abort());
    const url = `http://127.0.0.1:${server.address().port}`;
    await page.goto(url);
    await page.waitForFunction(() => document.querySelector("#sourceCount").textContent !== "-");
    assert.equal(await page.locator("#regionFilter option").count(), 1);
    assert.ok(!requests.some((request) => request.includes("listings-suwon")));
    await page.locator('[data-tab="briefing"]').click();
    assert.equal(await page.locator(".listing-card").count(), 24);
    await page.locator("#showMoreListings").click();
    assert.equal(await page.locator(".listing-card").count(), 48);
    await page.locator("#advancedFilters > summary").click();
    await page.locator("#priceMax").fill("80000");
    assert.ok(await page.evaluate(() => state.filtered.length > 0 && state.filtered.every((row) => row.price <= 80000)));
    await page.locator("#directionFilter").selectOption("남향");
    assert.ok(await page.evaluate(() => state.filtered.every((row) => row.direction === "남향")));
    await page.locator("#resetAdvanced").click();
    await page.locator("#advancedFilters > summary").click();
    await page.locator('[data-floor="중층"]').click();
    await page.locator('[data-floor="고층"]').click();
    assert.ok(await page.evaluate(() => state.filtered.every((row) => row.floorGroup === "저층")));
    assert.equal(await page.locator("#kpiCount").textContent(), `${await page.evaluate(() => state.filtered.length)}건`);
    await page.locator('[data-floor="전체"]').click();
    await page.locator("#typeFilterButton").click();
    const options = page.locator('#typeFilterMenu [data-multi-value]');
    const typeIndex = await options.evaluateAll((nodes) => nodes.findIndex((node) => node.textContent.includes("산울2단지") && node.textContent.includes("153A /")));
    assert.ok(typeIndex > 0);
    await options.nth(typeIndex).click();
    assert.ok(await page.evaluate(() => state.filtered.every((row) => row.complex.includes("산울2단지") && row.supplyArea === "153A")));
    assert.ok(await page.locator("#typeFilterMenu").isVisible());
    await page.locator('#typeFilterMenu [data-multi-value="전체"]').click();
    await page.locator("#typeFilterButton").click();
    await page.locator("#dealFilter").selectOption("전체");
    assert.ok(await page.locator("#priceKpis").isHidden());
    assert.equal(await page.locator("#dealPriceBreakdown tbody tr").count(), 3);
    assert.equal(await page.locator("#realTransactionBody > tr").count(), 15);
    await page.evaluate(() => scrollTo(0, document.querySelector("#briefingTab").offsetTop - document.querySelector("#mainToolbar").offsetHeight - 12));
    await page.screenshot({ path: path.join(output, "desktop-all.png") });
    await page.locator(".panel").filter({ has: page.locator("#realTransactionBody") }).screenshot({ path: path.join(output, "real-transactions.png") });
    await page.locator("#dealFilter").selectOption("매매");
    await page.locator(".listing-card .listing-history summary").first().click();
    await page.locator(".listing-card .plan-button").first().click();
    await page.waitForFunction(() => [...document.querySelectorAll("#floorplanImages img")].some((image) => image.complete && image.naturalWidth > 0));
    await page.locator(".modal-close").click();
    await page.locator(".listing-card .basket-button").first().click();
    await page.locator("#customerNameInput").fill("테스트 고객A");
    await page.locator("#customerPhoneInput").fill("000-0000-0001");
    await page.locator("[data-save-contact]").first().click();
    await page.locator("#customerNameInput").fill("테스트 고객B");
    await page.locator("#customerPhoneInput").fill("000-0000-0002");
    await page.locator("[data-save-contact]").first().click();
    assert.equal(await page.evaluate(() => state.contacts.length), 2);
    const brokerValue = await page.locator("[data-contact-broker] option").nth(1).getAttribute("value");
    await page.locator("[data-contact-broker]").selectOption(brokerValue);
    await page.locator('[data-contact-field="status"]').selectOption("연락완료");
    await page.locator('[data-contact-field="memo"]').fill("테스트 내부 메모");
    const wordPromise = page.waitForEvent("download", { timeout: 30000 });
    await page.locator("#exportCustomerDoc").click();
    await (await wordPromise).saveAs(path.join(output, "synthetic-customer.docx"));
    const downloadPromise = page.waitForEvent("download");
    await page.locator("#backupWork").click();
    const backup = await downloadPromise;
    const backupPath = path.join(output, "synthetic-work-backup.json");
    await backup.saveAs(backupPath);
    assert.equal(JSON.parse(await fs.readFile(backupPath, "utf8")).contacts.length, 2);
    await page.locator("#clearContacts").click();
    assert.equal(await page.evaluate(() => state.contacts.length), 1);
    await page.locator("#restoreWorkFile").setInputFiles(backupPath);
    await page.waitForFunction(() => state.contacts.length === 2);
    await page.reload();
    await page.waitForFunction(() => document.querySelector("#sourceCount").textContent !== "-");
    assert.equal(await page.evaluate(() => state.basket.length), 1);
    assert.equal(await page.evaluate(() => state.contacts.length), 2);
    await page.locator('[data-tab="briefing"]').click();
    await page.evaluate(() => scrollTo(0, document.querySelector("#listingGrid").offsetTop - document.querySelector("#mainToolbar").offsetHeight - 12));
    await page.screenshot({ path: path.join(output, "desktop-cards.png") });
    await page.locator('[data-tab="signage"]').click();
    assert.ok(await page.evaluate(() => {
      const bytes = document.querySelector("#signageCanvas").getContext("2d").getImageData(0, 0, 1080, 1920).data;
      return bytes.some((byte) => byte !== 0);
    }));
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('[data-tab="briefing"]').click();
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: path.join(output, "mobile-top.png") });
    const overflow = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, width: innerWidth }));
    assert.ok(overflow.scroll <= overflow.width + 1, JSON.stringify(overflow));
    await page.locator(".listing-card").first().scrollIntoViewIfNeeded();
    await page.screenshot({ path: path.join(output, "mobile-cards.png") });
    assert.deepEqual(errors, []);
    console.log(JSON.stringify({ passed: true, screenshots: output, checks: "region, pagination, budgets, direction, floors, type identity, deals, real table, plan, customer separation, backup merge, persistence, signage, mobile" }));
    await context.close();
  } finally {
    if (browser) await browser.close();
    await new Promise((resolve) => server.close(resolve));
  }
})().catch((error) => { console.error(error); process.exitCode = 1; });
